### PR TITLE
Get DeviceID added

### PR DESCRIPTION
**Pull request by ankushss**
React method to get the Device ID for both android and ios

### CODE REVIEW

**Comment by Gerlison** [comment]
This would be very helpful for testing the pushes for both platforms without relying on going native.

**Comment by Ghoral** [comment]
Can you also add event listener for notification? while tapping on the notification emit an event which returns a payload so that we can navigate to different screen based on the notification received. This is one of the most important functionality we are missing right now.

**Comment by billmote** [comment]
> Can you also add event listener for notification? while tapping on the notification emit an event which returns a payload so that we can navigate to different screen based on the notification received. This is one of the most important functionality we are missing right now.

URL handler is set when configuring the SDK and the functionality exists today.

**Comment by billmote** [comment]
Nice change. I'll get it prioritized in our backlog.

**Comment by Silinde87** [comment]
Is this feature planned to be added?

**Comment by billmote** [comment]
Yes. We're expecting a release very soon which will include the DeviceID getter.

**Comment by snama-sf** [comment]
This has been updated in the version 8.0.0

**Pull request closed without merging**
