### PR TITLE
Marketingcloudsdk 8.0 upgrade

### PR DESCRIPTION
**Pull request by ergenekonyigit**

### CODE REVIEW

**Comment by billmote** [comment]
Version 8.x of the SDK has not been tested with ReactNative.

**Comment by billmote** [comment]
Yes.

**Comment by douglasjunior** [comment]
Unable to run the app with React Native 0.68 and 0.69, because now Android SDK 31 is required.

```
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:673)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:660)
        at com.salesforce.marketingcloud.a.b.a(Unknown Source:10)
        at com.salesforce.marketingcloud.a.b.c(Unknown Source:40)
        at com.salesforce.marketingcloud.analytics.c.c$2.a(Unknown Source:190)
        at com.salesforce.marketingcloud.e.g.run(Unknown Source:17)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

Any updates on this?

**Comment by billmote** [comment]
Without making any external commitment: the updates are currently under peer review, will be tested, and released in the near future.

**Comment by mendesfelipe87** [comment]
Any news about this?

**Comment by srikanthnama** [comment]
Update is available now. Use the latest release for Android 12 support.

**Comment by mendesfelipe87** [comment]
@srikanthnama which version of the react native marketingcloud sdk should I use? still listing the 7.5 version as latest

**Comment by billmote** [comment]
https://github.com/salesforce-marketingcloud/react-native-marketingcloudsdk/blob/HEAD/CHANGELOG.md

**Comment by Silinde87** [comment]
Should we use 8.x.x marketingcloud sdk version? Last version listed on shared @billmote list is 7.4.3. Thanks!

**Comment by billmote** [comment]
No. An updated version of the React plugin is forthcoming, but this version will not work with 8.x.

**Pull request closed without merging**
